### ISSUE TITLE
screengrab: android.permission.CHANGE_CONFIGURATION

### ISSUE THREAD

**Issue by asterixorobelix** [fastlane/docs#789]
Adding the following permission to the Android Manifest as specified [here](https://docs.fastlane.tools/getting-started/android/screenshots/)
```
    <!-- Allows changing locales -->
    <uses-permission android:name="android.permission.CHANGE_CONFIGURATION" />
```

Android studio notifies you that this is a protected permission and only system level apps will be able to use this.

Running ```fastlane screengrab``` causes the following exception in the terminal:
```
Cobis-MacBook-Pro-2:afrikaburn cobi$ fastlane screengrab
[13:39:23]: fastlane detected a Gemfile in the current directory
[13:39:23]: however it seems like you don't use `bundle exec`
[13:39:23]: to launch fastlane faster, please use
[13:39:23]: 
[13:39:23]: $ bundle exec fastlane screengrab
[13:39:23]: 
[13:39:23]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[13:39:26]: The `aapt` command could not be found on your PATH
[13:39:26]: Please ensure that the Android SDK is installed and you have the build tools downloaded and present on your PATH

+-----------------------------+--------------------------------------+
|                   Summary for screengrab 2.116.1                   |
+-----------------------------+--------------------------------------+
| tests_package_name          | io.github.asterixorobelix.afrikabur  |
|                             | n.test                               |
| locales                     | ["en-US"]                            |
| clear_previous_screenshots  | false                                |
| output_directory            | fastlane/metadata/android            |
| skip_open_summary           | false                                |
| app_package_name            | io.github.asterixorobelix.afrikabur  |
|                             | n                                    |
| test_instrumentation_runner | android.support.test.runner.Android  |
|                             | JUnitRunner                          |
| ending_locale               | en-US                                |
| device_type                 | phone                                |
| exit_on_test_failure        | true                                 |
| reinstall_app               | false                                |
+-----------------------------+--------------------------------------+

[13:39:27]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[13:39:27]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[13:39:27]: $ /usr/local/bin/adb devices -l
[13:39:27]: ▸ List of devices attached
[13:39:27]: ▸ PL2GARH871000269       device usb:337641472X product:Plate2_00WW model:Nokia_6_1 device:PL2_sprout transport_id:6
[13:39:27]: $ /usr/local/bin/adb -s PL2GARH871000269 shell echo \$EXTERNAL_STORAGE
[13:39:27]: ▸ /sdcard
[13:39:27]: Cleaning screenshots on device
ls: /sdcard/io.github.asterixorobelix.afrikaburn/screengrab: No such file or directory
[13:39:27]: Exit status: 1
ls: /data/data/io.github.asterixorobelix.afrikaburn/app_screengrab: Permission denied
[13:39:27]: Exit status: 1
[13:39:27]: To not be asked about this value, you can specify it using 'app_apk_path'
[13:39:27]: Select your debug app APK
1. app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
2. app/build/outputs/apk/release/app-release-unsigned.apk
3. app/build/outputs/apk/debug/app-debug.apk
?  1
[13:39:59]: To not be asked about this value, you can specify it using 'tests_apk_path'
[13:39:59]: Select your debug tests APK
1. app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
2. app/build/outputs/apk/release/app-release-unsigned.apk
3. app/build/outputs/apk/debug/app-debug.apk
?  1
[13:40:09]: The `aapt` command could not be found on your system, so your app APK could not be validated
[13:40:09]: Installing app APK
[13:40:09]: $ /usr/local/bin/adb -s PL2GARH871000269 install -t -r app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
[13:40:13]: ▸ Success
[13:40:13]: Installing tests APK
[13:40:13]: $ /usr/local/bin/adb -s PL2GARH871000269 install -t -r app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
[13:40:15]: ▸ Success
[13:40:15]: Granting the permission necessary to change locales on the device
[13:40:15]: $ /usr/local/bin/adb -s PL2GARH871000269 shell pm grant io.github.asterixorobelix.afrikaburn android.permission.CHANGE_CONFIGURATION
[13:40:15]: ▸ Security exception: Package io.github.asterixorobelix.afrikaburn has not requested permission android.permission.CHANGE_CONFIGURATION
[13:40:15]: ▸ java.lang.SecurityException: Package io.github.asterixorobelix.afrikaburn has not requested permission android.permission.CHANGE_CONFIGURATION
[13:40:15]: ▸ at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:379)
[13:40:15]: ▸ at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1515)
[13:40:15]: ▸ at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:96)
[13:40:15]: ▸ at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2218)
[13:40:15]: ▸ at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:6153)
[13:40:15]: ▸ at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1730)
[13:40:15]: ▸ at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:217)
[13:40:15]: ▸ at android.os.ShellCommand.exec(ShellCommand.java:103)
[13:40:15]: ▸ at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22576)
[13:40:15]: ▸ at android.os.Binder.shellCommand(Binder.java:634)
[13:40:15]: ▸ at android.os.Binder.onTransact(Binder.java:532)
[13:40:15]: ▸ at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2849)
[13:40:15]: ▸ at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4531)
[13:40:15]: ▸ at android.os.Binder.execTransact(Binder.java:731)
Security exception: Package io.github.asterixorobelix.afrikaburn has not requested permission android.permission.CHANGE_CONFIGURATION

java.lang.SecurityException: Package io.github.asterixorobelix.afrikaburn has not requested permission android.permission.CHANGE_CONFIGURATION
at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:379)
at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1515)
at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:96)
at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2218)
at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:6153)
at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1730)
at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:217)
at android.os.ShellCommand.exec(ShellCommand.java:103)
at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22576)
at android.os.Binder.shellCommand(Binder.java:634)
at android.os.Binder.onTransact(Binder.java:532)
at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2849)
at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4531)
at android.os.Binder.execTransact(Binder.java:731)
[13:40:15]: Exit status: 255

[!] Exit status: 255
```

**Comment by asterixorobelix** [comment]
After rebuilding the debug apk and telling the manifest file to ignore protected permissions, as discussed [here](https://stackoverflow.com/questions/52207055/fastlane-screengrab-has-not-requested-permission-android-permission-change-con), I now have a different erro

**Comment by asterixorobelix** [comment]
How does one get the app to launch and take screenshots? My unit test is:
```
@ClassRule
val localeTestRule = LocaleTestRule()

@Rule
var activityRule = ActivityTestRule(MainActivity::class.java)

class ExampleUnitTest {
    @Test
    fun takeScreenshots(){
        Screengrab.screenshot("1")
    }
}
```

**Comment by janpio** [comment]
You should create a new issue at https://github.com/fastlane/fastlane/issues and fill the bug report template - then I (and others) should have enough information to help you. I have used screengrab just a few weeks ago, so this should be solvable. Thanks.
