### ISSUE TITLE
Fastlane upload to testflight is failing

### ISSUE THREAD

**Issue by userException** [fastlane/docs#989]
**Version:** 2.162.0

Error:  Build is not in an externally assignable state.

**Full trace:**

Traceback (most recent call last):
	34: from /usr/local/bin/fastlane:23:in `<main>'
	33: from /usr/local/bin/fastlane:23:in `load'
	32: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/bin/fastlane:23:in `<top (required)>'
	31: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	30: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	28: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	26: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	25: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	24: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	16: from Fastfile:174:in `block (2 levels) in parsing_binding'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:27:in `run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/pilot/lib/pilot/build_manager.rb:61:in `upload'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/pilot/lib/pilot/build_manager.rb:171:in `distribute'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/pilot/lib/pilot/build_manager.rb:398:in `distribute_build'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/models/build.rb:140:in `add_beta_groups'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `add_beta_groups_to_build'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:191:in `add_beta_groups_to_build'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/api_client.rb:124:in `post'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/api_client.rb:188:in `handle_response': [!] Build is not assignable. - Build is not in an externally assignable state. (Spaceship::UnexpectedResponse)

**Comment by userException** [comment]
Looks like something to do with Bitcode and Symbol files. I disabled both from gymfile and it worked.

include_bitcode(false)

include_symbols(false)
